# Generated by Django 6.0.2 on 2026-02-16 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_researchsession_researchfinding_mediaresource"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "concept",
                    models.CharField(
                        help_text="The topic/concept to build a curriculum around",
                        max_length=300,
                    ),
                ),
                ("grade_level", models.IntegerField(default=5)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "duration_weeks",
                    models.IntegerField(default=2, help_text="Number of weeks (1-5)"),
                ),
                (
                    "lessons_per_week",
                    models.IntegerField(default=2, help_text="Lessons per week (1-3)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("outline_ready", "Outline Ready"),
                            ("generating", "Generating Lessons"),
                            ("complete", "Complete"),
                            ("published", "Published"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "outline",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-generated week-by-week outline",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_curricula",
                        to="core.kidprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curriculum_plans",
                        to="content.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order within the week"),
                ),
                ("learning_objectives", models.TextField(blank=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_entry",
                        to="content.lesson",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_lessons",
                        to="content.curriculumplan",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number", "order"],
                "unique_together": {("curriculum", "lesson")},
            },
        ),
    ]
