# Generated by Django 6.0.2 on 2026-02-12 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⭐', max_length=50)),
                ('badge_type', models.CharField(choices=[('lesson_complete', 'Lesson Complete'), ('quiz_ace', 'Quiz Ace'), ('streak', 'Streak'), ('explorer', 'Explorer'), ('bookworm', 'Bookworm'), ('first_steps', 'First Steps')], max_length=20)),
                ('criteria', models.JSONField(default=dict, help_text='Conditions to earn this badge')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='core.kidprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KidBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.badge')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.kidprofile')),
            ],
            options={
                'unique_together': {('kid', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.kidprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.lesson')),
            ],
            options={
                'verbose_name_plural': 'lesson progress',
                'unique_together': {('kid', 'lesson')},
            },
        ),
    ]
