# Generated by Django 6.0.2 on 2026-02-15 23:33

from django.db import migrations


def seed_badges(apps, schema_editor):
    Badge = apps.get_model("progress", "Badge")
    badges = [
        {"name": "First Steps", "description": "Complete your first lesson!", "icon": "👣", "badge_type": "first_steps"},
        {"name": "Quiz Whiz", "description": "Score 100% on a quiz!", "icon": "🏆", "badge_type": "quiz_ace"},
        {"name": "On Fire!", "description": "Keep a 7-day learning streak!", "icon": "🔥", "badge_type": "streak"},
        {"name": "Explorer", "description": "Complete lessons in 3 different subjects!", "icon": "🧭", "badge_type": "explorer"},
        {"name": "Bookworm", "description": "Write 5 journal entries!", "icon": "📖", "badge_type": "bookworm"},
        {"name": "Lesson Master", "description": "Complete 10 lessons!", "icon": "⭐", "badge_type": "lesson_complete"},
    ]
    for b in badges:
        Badge.objects.get_or_create(name=b["name"], defaults=b)


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_badges, migrations.RunPython.noop),
    ]
