# Generated by Django 6.0.2 on 2026-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="context_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("lesson", "Lesson Help"),
                    ("quiz_help", "Quiz Help"),
                    ("canvas", "Canvas"),
                    ("math", "Math Practice"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
