# Generated by Django 6.0.2 on 2026-02-12 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='What the kid wrote')),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.kidprofile')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='content.lesson')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
